### ISSUE TITLE
建议：将 datasets/world_for_china.gz 打包进Pypi

### ISSUE THREAD

**Issue by tcztzy** [yuanzhoulvpi2017/chinamap#1]
可以使用[`include_package_data`](https://setuptools.pypa.io/en/latest/userguide/datafiles.html)实现
```python
setup(
    include_package_data=True,
)
```

**Comment by yuanzhoulvpi2017** [comment]
感谢建议，目前已经把包更新了（2022-08-30 版本1.0.07），再也不需要手动下载对应的数据。
再次感谢老哥～
